// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncServer.Models;

namespace SyncServer.Migrations
{
    [DbContext(typeof(SyncServerContext))]
    partial class SyncServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("SyncServer.Models.DynamicEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ProjectId");

                    b.Property<string>("ProjectTableName");

                    b.Property<int>("RowVersion");

                    b.HasKey("Id");

                    b.ToTable("DynamicEntities");
                });

            modelBuilder.Entity("SyncServer.Models.SchemaDefinition", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Columns");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ProjectId");

                    b.Property<string>("ProjectTableName");

                    b.Property<int>("RowVersion");

                    b.HasKey("Id");

                    b.ToTable("SchemaDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
